/**********************************************************************
 * Extern for soundManager
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var soundManager = {
  "_debug": function () {},
  "_externalInterfaceOK": function () {},
  "_setSandboxType": function () {},
  "_wD": function () {},
  "_writeDebug": function () {},
  "altURL": {},
  "audioFormats": {
    "flac": {
      "required": {},
      "type": {}
    },
    "mp3": {
      "required": {},
      "type": {}
    },
    "mp4": {
      "related": {},
      "required": {},
      "type": {}
    },
    "ogg": {
      "required": {},
      "type": {}
    },
    "opus": {
      "required": {},
      "type": {}
    },
    "wav": {
      "required": {},
      "type": {}
    }
  },
  "beginDelayedInit": function () {},
  "canPlayLink": function () {},
  "canPlayMIME": function () {},
  "canPlayURL": function () {},
  "clearOnPosition": function () {},
  "createSound": function () {},
  "debugID": {},
  "debugURLParam": {},
  "defaultOptions": {
    "autoLoad": {},
    "autoPlay": {},
    "from": {},
    "loops": {},
    "multiShot": {},
    "multiShotEvents": {},
    "onerror": {},
    "onfinish": {},
    "onid3": {},
    "onload": {},
    "onpause": {},
    "onplay": {},
    "onposition": {},
    "onresume": {},
    "onstop": {},
    "pan": {},
    "playbackRate": {},
    "position": {},
    "stream": {},
    "to": {},
    "type": {},
    "usePolicyFile": {},
    "volume": {},
    "whileloading": {},
    "whileplaying": {}
  },
  "destroySound": function () {},
  "destruct": function () {},
  "didFlashBlock": {},
  "disable": function () {},
  "enabled": {},
  "features": {
    "buffering": {},
    "eqData": {},
    "movieStar": {},
    "peakData": {},
    "waveformData": {}
  },
  "filePattern": {},
  "filePatterns": {
    "flash8": {},
    "flash9": {}
  },
  "flash": {},
  "flash9Options": {
    "isMovieStar": {},
    "onbufferchange": {},
    "ondataerror": {},
    "onfailure": {},
    "useEQData": {},
    "usePeakData": {},
    "useWaveformData": {}
  },
  "getMemoryUse": function () {},
  "getMovie": function () {},
  "getMoviePercent": function () {},
  "getSoundById": function () {},
  "hasHTML5": {},
  "html5": {
    "usingFlash": {}
  },
  "html5Only": {},
  "id": {},
  "ignoreFlash": {},
  "load": function () {},
  "mimePattern": {},
  "movieID": {},
  "movieStarOptions": {
    "bufferTime": {},
    "duration": {},
    "onconnect": {},
    "serverURL": {}
  },
  "movieURL": {},
  "mute": function () {},
  "muteAll": function () {},
  "muted": {},
  "oMC": {},
  "ok": function () {},
  "onPosition": function () {},
  "onposition": function () {},
  "onready": function () {},
  "ontimeout": function () {},
  "pause": function () {},
  "pauseAll": function () {},
  "play": function () {},
  "reboot": function () {},
  "reset": function () {},
  "resume": function () {},
  "resumeAll": function () {},
  "sandbox": {},
  "setPan": function () {},
  "setPlaybackRate": function () {},
  "setPosition": function () {},
  "setVolume": function () {},
  "setup": function () {},
  "setupOptions": {
    "allowScriptAccess": {},
    "bgColor": {},
    "consoleOnly": {},
    "debugFlash": {},
    "debugMode": {},
    "flashLoadTimeout": {},
    "flashPollingInterval": {},
    "flashVersion": {},
    "forceUseGlobalHTML5Audio": {},
    "html5PollingInterval": {},
    "html5Test": {},
    "idPrefix": {},
    "ignoreMobileRestrictions": {},
    "noSWFCache": {},
    "preferFlash": {},
    "url": {},
    "useConsole": {},
    "useFlashBlock": {},
    "useHTML5Audio": {},
    "useHighPerformance": {},
    "waitForWindowLoad": {},
    "wmode": {}
  },
  "soundIDs": {},
  "sounds": {},
  "start": function () {},
  "stop": function () {},
  "stopAll": function () {},
  "supported": function () {},
  "swfLoaded": {},
  "toggleMute": function () {},
  "togglePause": function () {},
  "unload": function () {},
  "unmute": function () {},
  "unmuteAll": function () {},
  "useAltURL": {},
  "version": {},
  "versionNumber": {}
};
/**********************************************************************
 * End Generated Extern for soundManager
/**********************************************************************/